# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036fe064a1982ee8fd19e6535aee8451883dbfe518cad259f5b2213915e1941ff221fbe318b7fba0b80d716346ff46444c5ca8b1fabe9d9496269e7f24bf00b0

test:
  secret_key_base: b0d3e0808a3ace0732abe12fba11d1a226219643b1cce5889dd7dc4fbd8a7d71a271bc6ee492f42909b8a97ed7205af8aaee8176892a30b1b1962048fda2c18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
